### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by keisuke0106** [keisuke0106/furima_28294#9]
フリマアプリのURL
https://furima-28294-28294.herokuapp.com/

Basic認証のIDとパスワード
ID: kisk  Pass: 2065

購入用カードの番号・期限・セキュリティコード
4242424242424242
12/24
123

出品者用のメールアドレスとパスワード
testdesu@test.com
kisk0106

購入者用のメールアドレスとパスワード
testnanodesu@test.com
kisk0000

**Comment by mo1015** [comment]
長崎さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
